### ISSUE TITLE
usbtmc Error -410: "Query Interrupted"

### ISSUE THREAD

**Issue by kaschneider** [python-ivi/python-usbtmc#35]
I am trying to communicate with a Keysight network analyzer and a Raspberry Pi 3 (through Python 3 and usbtmc). My current code looks like this:

`import usbtmc`
`import time`

`instr = usbtmc.Instrument(0x2a8d, 0x5c18)`
`print(instr.ask("*IDN?"))`

`instr.timeout = 2000`
`instr.write("CALC:PAR2:DEF S21")`
`instr.write("CALC:PAR1:SEL")`
`instr.write("CALC:FORM MLOGarithmic")`
`instr.write("FREQ:STAR MIN")`
`instr.write("FREQ:STOP 21E9")`
`instr.write("AVER:COUN 500")`
`#instr.ask("CALC:DATA:FDATa?")  #this line does not work`

`#reset device after each run to avoid having the 'operation timed out' error`
`instr.clear(25)`

These commands are just setting up a lot of formatting on the device. Unfortunately I keep getting an error on my device itself that says "Error -410: Query INTERRUPTED", which I take to mean that something else started before the previous command finished. I think this may be solved with the timeout but am not sure. Any ideas?

**Comment by alexforencich** [comment]
Query interrupted means that you sent a query command but then did something other than reading.  Say, you write *IDN? and then, instead of reading, you write something else.  It's possible that the read timed out.  In which case, you should try increasing the timeout.  You could also try splitting the ask into a write and a read with a delay in between.  It's also possible that the unit is expecting multiple reads.
